services:
  api:
    image: ghcr.io/hieunguyen2604/todo-api:latest
    environment:
      - DATABASE_URL=Host=db;Port=5432;Database=todo_db;Username=postgres;Password=postgres
      - REDIS_URL=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  api-2:
    image: ghcr.io/hieunguyen2604/todo-api:latest
    environment:
      - DATABASE_URL=Host=db;Port=5432;Database=todo_db;Username=postgres;Password=postgres
      - REDIS_URL=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    image: ghcr.io/hieunguyen2604/todo-frontend:latest
    environment:
      - VITE_API_URL=/api
    ports:
      - "80:80"
    depends_on:
      - api
      - api-2

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
